Host *
    ServerAliveInterval 30
    ServerAliveCountMax 3
    TCPKeepAlive yes
    AddKeysToAgent yes
    HashKnownHosts yes
    UpdateHostKeys yes
    ForwardAgent no
    ControlMaster auto
    ControlPath ~/.ssh/controlmasters/%r@%h:%p
